version: "3"
services:
  ttdeye-stock-web:
    image: 18600285979/ttdeye-stock:0.0.1-SNAPSHOT
    ports:
      - 8081:8081
    container_name: ttdeye-stockv0.0.1
    volumes:
      - /data/logs/ttdeye-stock:/data/logs/ttdeye-stock
    restart: always

  ttdeye-stock-nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    container_name: ttdeye-nginx
    volumes:
      - ~/nginx/www:/usr/share/nginx/html
      - ~/conf/nginx.conf:/etc/nginx/nginx.conf
      - ~/nginx/logs:/var/log/nginx
      - /etc/nginx/conf.d:/etc/nginx/conf.d
    restart: always

  ttdeye-stock-redis:
    image: redis
    ports:
      - 6379:6379
    container_name: ttdeye-redis
    volumes:
      - /data/redis/data:/data
    command:
      [
        "--character-set-server=utf8mb4",
        "redis-server",
        "--appendonly yes",
        "--requirepass ttdeye"
      ]
    restart: always

  ttdeye-stock-mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    container_name: ttdeye-mysql
    volumes:
      - /data/mysql/conf:/etc/mysql/conf.d
      - /data/mysql/logs:/logs
      - /data/mysql/data:/var/lib/mysql
    command:
      [
        "-e",
        "MYSQL_ROOT_PASSWORD=ttdeye"
      ]
    restart: always